name: Create an issue
on:
    pull_request:
        branches:
            - '*'
    
jobs:
    create-issue:
        uses: CQCL/hugrverse-actions/.github/workflows/create-issue.yml@ab/create-issue
        secrets:
            GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
        with:
            title: "Test issue, please ignore"
            body: "This is a test issue for PR #24."
            unique-label: "test"
            # Optional list of labels to add to the issue.
            other-labels: "invalid,wontfix"